name: RelluEssentials
main: main.java.de.relluem94.minecraft.server.spigot.essentials.RelluEssentials
version: 1.0
api-version: 1.13
commands:
    0:
        description: Change your Gamemode with this shorthand to Survival
        usage: /0
    1:
        description: Change your Gamemode with this shorthand to Creative
        usage: /1
    2:
        description: Change your Gamemode with this shorthand to Adventure
        usage: /2
    3:
        description: Change your Gamemode with this shorthand to Spectator
        usage: /3
    fly:
        description: Toggle your fly mode
        usage: /fly
    craft:
        description: Open Craftingbench protable
        usage: /craft
    cookie:
        description: Share a Cookie (with your best friend)
        usage: /cookie
    sun:
        description: Change the Weather (Tutti Frutti Summer Love)
        usage: /sun
    rain:
        description: Change the Weather (Rainy Days and Mondays)
        usage: /rain
    storm:
        description: Change the Weather (Call it stormy Monday)
        usage: /storm
    spawn:
        description: Teleport to the World Spawn
        usage: /spawn
    day:
        description: Change time to Day
        usage: /day
    night:
        description: Change time to Night
        usage: /night
    enderchest:
        description: Open the Enderchest
        usage: /enderchest
    inv:
        description: Open the Inventory
        usage: /inv
    setGroup:
        description: Set Player Group 
        usage: /setGroup
    nick:
        description: Set Player Name 
        usage: /nick
    suicide:
        description: Kill yourself
        usage: /suicide
    more:
        description: Give yourself more of the item in your Mainhand
        usage: /more
    repair:
        description: Repair your Tool in the Mainhand
        usage: /repair
    home:
        description: Teleport to your Bedspawn
        usage: /home
    enchanttest:
        description: Test Echnantments
        usage: /enchanttest


